var letterValues = {
    "a": {
        "hash": 2,
        "value": 1
    },
    "b": {
        "hash": 3,
        "value": 3
    },
    "c": {
        "hash": 5,
        "value": 3
    },
    "d": {
        "hash": 7,
        "value": 2
    },
    "e": {
        "hash": 11,
        "value": 1
    },
    "f": {
        "hash": 13,
        "value": 4
    },
    "g": {
        "hash": 17,
        "value": 2
    },
    "h": {
        "hash": 19,
        "value": 4
    },
    "i": {
        "hash": 23,
        "value": 1
    },
    "j": {
        "hash": 29,
        "value": 8
    },
    "k": {
        "hash": 31,
        "value": 5
    },
    "l": {
        "hash": 37,
        "value": 1
    },
    "m": {
        "hash": 41,
        "value": 3
    },
    "n": {
        "hash": 43,
        "value": 1
    },
    "o": {
        "hash": 47,
        "value": 1
    },
    "p": {
        "hash": 53,
        "value": 3
    },
    "q": {
        "hash": 59,
        "value": 10
    },
    "r": {
        "hash": 61,
        "value": 1
    },
    "s": {
        "hash": 67,
        "value": 1
    },
    "t": {
        "hash": 71,
        "value": 1
    },
    "u": {
        "hash": 73,
        "value": 1
    },
    "v": {
        "hash": 79,
        "value": 4
    },
    "w": {
        "hash": 83,
        "value": 4
    },
    "x": {
        "hash": 89,
        "value": 8
    },
    "y": {
        "hash": 97,
        "value": 4
    },
    "z": {
        "hash": 101,
        "value": 10
    }
};

var dictionary = [
    "achievement",
    "acid",
    "action",
    "adventure",
    "allspark",
    "ammo",
    "arpg",
    "assassin",
    "asteroid",
    "autosave",
    "avatar",
    "avenger",
    "beta",
    "blade",
    "blast",
    "block",
    "blood",
    "boss",
    "buff",
    "bullet",
    "buster",
    "checkpoint",
    "cheese",
    "chrono",
    "claptrap",
    "class",
    "closed",
    "console",
    "controller",
    "cooldown",
    "corruption",
    "counter",
    "cover",
    "cpu",
    "crafting",
    "creed",
    "crouch",
    "crpg",
    "cutscene",
    "cutting",
    "damage",
    "difficulty",
    "dig",
    "dlc",
    "dodge",
    "doublejump",
    "drm",
    "dungeon",
    "dweller",
    "early",
    "edge",
    "emergent",
    "endings",
    "episodic",
    "escort",
    "esports",
    "event",
    "exclusive",
    "exploit",
    "explosion",
    "fall",
    "farm",
    "farming",
    "fasttravel",
    "field",
    "fight",
    "finished",
    "fireball",
    "fog",
    "free",
    "game",
    "ganon",
    "gauntlet",
    "gem",
    "generation",
    "ghost",
    "god",
    "gpu",
    "grenade",
    "griefer",
    "grinding",
    "gun",
    "halo",
    "hardmode",
    "healer",
    "health",
    "horror",
    "ifrit",
    "indie",
    "infinity",
    "instance",
    "invader",
    "joystick",
    "jrpg",
    "jump",
    "keyblade",
    "keyboard",
    "kill",
    "lag",
    "lane",
    "leroy",
    "level",
    "lightning",
    "link",
    "live",
    "ludology",
    "mage",
    "magus",
    "mana",
    "mario",
    "masamune",
    "master",
    "matchmaking",
    "materia",
    "megaman",
    "microtransactions",
    "middleware",
    "midgar",
    "mission",
    "mmorpg",
    "mob",
    "moba",
    "mode",
    "monster",
    "mouse",
    "mouselook",
    "multiple",
    "myst",
    "nerf",
    "nintendo",
    "noob",
    "npc",
    "nvidia",
    "openworld",
    "optimus",
    "overpowered",
    "overshield",
    "pacman",
    "pass",
    "pellet",
    "permadeath",
    "persistent",
    "pickaxe",
    "pierce",
    "pixel",
    "plasma",
    "play",
    "poison",
    "port",
    "potion",
    "procedural",
    "puzzle",
    "pve",
    "pvp",
    "quest",
    "quick",
    "raid",
    "realtime",
    "replay",
    "retrogaming",
    "rig",
    "rocket",
    "roguelike",
    "romance",
    "rpg",
    "season",
    "shield",
    "shoot",
    "shovel",
    "simulator",
    "sli",
    "sliding",
    "smash",
    "souls",
    "spawn",
    "speedrun",
    "spread",
    "sprint",
    "stealth",
    "strategy",
    "streak",
    "summon",
    "super",
    "survival",
    "sword",
    "system",
    "tactics",
    "tank",
    "tesseract",
    "theory",
    "time",
    "touchscreen",
    "triforce",
    "uppercut",
    "vault",
    "walljump",
    "war",
    "warrior",
    "wasd",
    "wasteland",
    "world",
    "zelda",
    "zombie"
];